In [9]:
from collections import Counter
l = ["a", "b", "r", "b", "b"]

c = Counter(l)
print(c)
sorted(set(l), key=lambda x: c[x], reverse=True)

Counter({'b': 3, 'a': 1, 'r': 1})


['b', 'a', 'r']

In [12]:
words = [1, 2, 3, 4]
token = [str(word) for word in words]
type(token)

list

In [16]:
import torch
a = torch.tensor([1,2,3])
print(a.tolist())

[1, 2, 3]


In [21]:
words = ["the", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog"]
print(words[4-2:4] + words[4+1:4+2+1])

['brown', 'fox', 'over', 'the']


In [23]:
a = []
a += ["0"]*3
print(a)

['0', '0', '0']


In [26]:
col = 3
fil = 2
similarities: torch.Tensor = torch.zeros((fil,col))
print(similarities)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
import torch
batch_size = 2
n_samples = 3

noise_dist: torch.Tensor = torch.ones(torch.tensor(15))

# Sample words from our noise distribution
# TODO
noise_dist = noise_dist.expand((batch_size, noise_dist.shape[0]))
noise_words: torch.Tensor = torch.multinomial(noise_dist, n_samples)

print(noise_dist)
print(noise_dist.size())
print(noise_words)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([2, 15])
tensor([[ 7,  3,  6],
        [10,  4, 13]])


In [55]:
a = torch.tensor([[8,9],[4,3]])
b = torch.tensor([[4,5],[2,3]])
print(a.unsqueeze(1))
print(b.unsqueeze(2))
c = torch.bmm(a.unsqueeze(1),b.unsqueeze(2))
print(c)
c = c.squeeze()
print(c)

tensor([[[8, 9]],

        [[4, 3]]])
tensor([[[4],
         [5]],

        [[2],
         [3]]])
tensor([[[77]],

        [[17]]])
tensor([77, 17])


In [29]:
# Ejemplo con N=5, d=3
N, d = 5, 3
A = torch.randn(N, d)  # (N, d) -> Filas son vectores
B = torch.randn(d, N)  # (d, N) -> Columnas son vectores

# Reshape para usar bmm
A_reshaped = A.unsqueeze(1)  # (N, 1, d)
B_reshaped = B.T.unsqueeze(2)  # (N, d, 1) -> Transponer B para alinear con A

# Batch Matrix Multiplication (bmm)
dot_products = torch.bmm(A_reshaped, B_reshaped).squeeze()  # (N, 1, 1) -> (N,)

print(dot_products)  # Tensor de tamaño (N,)

tensor([-4.5254,  0.9362,  2.6510,  0.3166,  2.1034])


In [49]:
input = torch.tensor([[8,9],[4,3]])
output = torch.tensor([[[0,1],[2,3],[4,1]], [[5,3],[8,2],[4,1]]])

input_unsqueeze = input.unsqueeze(1)
# print(input_unsqueeze)
# print(input_unsqueeze.shape)

o_t = output.transpose(1,2)

c = torch.bmm(input_unsqueeze, o_t).squeeze()
print(c.shape)
c = c.sum(dim=1)
print(c)

torch.Size([2, 3])
tensor([93, 86])


In [53]:
b = torch.tensor([[4,5],[2,3]])
print(b.unsqueeze(1))
print(b.unsqueeze(2))

tensor([[[4, 5]],

        [[2, 3]]])
tensor([[[4],
         [5]],

        [[2],
         [3]]])
